const ActionType = {
 
  CATEGORIES_SET:"CATEGORIES_SET",

  USERS_PUT_USER: "USERS_PUT_USER",
  USERS_PUT_USERS_HOME: "USERS_PUT_USERS_HOME",
  USERS_PUT_ISAUTH: "USERS_PUT_ISAUTH",
   
  APP_MOBILE: "APP_MOBILE",
  APP_SOCKET: "APP_SOCKET", 
  APP_WORK_DATA: "APP_WORK_DATA",

  APP_SIDE_MENU:"APP_SIDE_MENU",
  APP_PAGES_SCREEN:"APP_PAGES_SCREEN",
  APP_SUBPAGES_SCREEN:"APP_SUBPAGES_SCREEN", 
  POPUP_LOGIN_VISIBLE:"POPUP_LOGIN_VISIBLE",
  POPUP_LOGIN_ENTER:"POPUP_LOGIN_ENTER",
  APP_LOADING:"APP_LOADING", 

  DIALOGS_SET_ACTIVE:"DIALOGS_SET_ACTIVE",

  ROOMS_SET_ACTIVE:"ROOMS_SET_ACTIVE",
}

export default ActionType;