const ActionType = {
 
  CATEGORIES_SET:"CATEGORIES_SET",

  USERS_PUT_USER:"USERS_PUT_USER",
  USERS_PUT_ISAUTH:"USERS_PUT_ISAUTH",
   
  APP_MOBILE:"APP_MOBILE",
  APP_SIDE_MENU:"APP_SIDE_MENU",
  APP_PAGES_SCREEN:"APP_PAGES_SCREEN",
  APP_SUBPAGES_SCREEN:"APP_SUBPAGES_SCREEN", 

  POPUP_LOGIN_VISIBLE:"POPUP_LOGIN_VISIBLE",
  POPUP_LOGIN_ENTER:"POPUP_LOGIN_ENTER",
  APP_LOADING:"APP_LOADING", 
}

export default ActionType;